//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWHOUSE_REBUILD_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNghe
    {
        public int ID { get; set; }
        public string TuaDe11 { get; set; }
        public string NoiDung11 { get; set; }
        public string TuaDe12 { get; set; }
        public string NoiDung12 { get; set; }
        public string Hinh1 { get; set; }
        public string TuaDe2 { get; set; }
        public string NoiDung2 { get; set; }
        public string Hinh2 { get; set; }
        public string TuaDeChinh { get; set; }
        public string TrichDan { get; set; }
    }
}
