//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWHOUSE_REBUILD_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUAN()
        {
            this.KTS_DUAN = new HashSet<KTS_DUAN>();
        }
    
        public int IDDuan { get; set; }
        public string TenDuan { get; set; }
        public Nullable<int> IDTheLoaiDuAn { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public string NoiDung { get; set; }
        public string Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KTS_DUAN> KTS_DUAN { get; set; }
    }
}
