//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWHOUSE_REBUILD_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KT()
        {
            this.KTS_DUAN = new HashSet<KTS_DUAN>();
        }
    
        public int IDKTS { get; set; }
        public string TuaDe { get; set; }
        public string TuaDePhu { get; set; }
        public string NoiDung { get; set; }
        public string Hinh { get; set; }
        public string GioiThieuTrai { get; set; }
        public string GioiThieuPhai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KTS_DUAN> KTS_DUAN { get; set; }
    }
}
