//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWHOUSE_REBUILD_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTS_DUAN
    {
        public int ID { get; set; }
        public Nullable<int> IDDuan { get; set; }
        public Nullable<int> IDKTS { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual KT KT { get; set; }
    }
}
